export const PORTFOLIO_DATA = {
  personal: {
    name: "Awanish Kumar Rai",
    title: "B.Tech CSE (Class of 2027)",
    subtitle: "Software Engineer | Competitive Programmer",
    email: "awanishrai420@gmail.com",
    phone: "+91-6283642238",
    location: "India",
  },
  education: {
    current: {
      institution: "Lovely Professional University",
      program: "B.Tech Computer Science and Engineering",
      specialization: "Computer Science",
      cgpa: "8.29",
      expectedGraduation: "2027",
      highlights: [
        "Data Structures & Algorithms",
        "Operating Systems",
        "Computer Networks",
        "Database Management Systems",
      ],
    },
    previous: [
      {
        institution: "Sant Longowal Institute of Engineering and Technology",
        program: "Diploma in Chemical Technology",
        level: "Diploma",
        cgpa: "9.15",
        year: "2023",
        score: "CGPA 9.15",
      },
      {
        institution: "Cambridge Senior Secondary School",
        program: "Matriculation",
        level: "10th",
        percentage: "85.8%",
        year: "2020",
        score: "85.8%",
      },
    ],
  },
  socials: {
    github: "https://github.com/awanishkrai",
    linkedin: "https://linkedin.com/in/awanish-rai-9296ab221",
    codeforces: "https://codeforces.com/profile/Awanish_Rai",
    codechef: "https://codechef.com/users/master_magnus",
  },
  skills: {
    Languages: ["Python", "C++", "Java", "JavaScript", "PHP"],
    Frontend: ["React.js", "Redux", "Tailwind CSS", "HTML5", "CSS3"],
    Backend: ["Django", "Flask", "Node.js", "REST APIs"],
    Databases: ["PostgreSQL", "MySQL", "MongoDB"],

  },
  competitiveProgramming: [
    {
      platform: "LeetCode",
      rating: 1635,
      label: "Current rating",
      color: "#eab308",
      url: "https://leetcode.com",
    },
    {
      platform: "CodeChef",
      rating: 1434,
      label: "2★ rating",
      color: "#f97316",
      url: "https://www.codechef.com/users/master_magnus",
    },
    {
      platform: "Codeforces",
      rating: 1285,
      label: "Pupil",
      color: "#3b82f6",
      url: "https://codeforces.com/profile/Awanish_Rai",
    },
  ],
  projects: [
    {
      name: "OS Based Room Booking System",
      description:
        "Concurrent backend room booking system that safely handles overlapping booking requests.",
      technologies: "Python, Django REST Framework, Threading, Semaphores, PostgreSQL",
      highlights: [
        "Implements FCFS scheduling with semaphores and multithreading",
        "Prevents race conditions during simultaneous booking requests",
        "Provides a clean REST API for room search and booking",
      ],
      github: "https://github.com/awanishkrai/Booking_System_API",
      readme: "# Booking_System_API\n",
    },
    {
      name: "Adhyay",
      description:
        "Collaborative book platform for exploring a vast collection of books and joining club discussions.",
      technologies: "Django, Python, HTML, CSS, JavaScript",
      image: "/projects/adhyay.png",
      highlights: [
        "User authentication with personalized readlists",
        "Book search and exploration with club discussions",
        "Add and manage books collaboratively",
      ],
      github: "https://github.com/awanishkrai",
    },
    {
      name: "Neo Gamified Learning",
      description:
        "Gamified learning platform with XP progression, leaderboards, and quest-based course completion.",
      technologies: "React, Node.js, Express, MongoDB, Tailwind CSS",
      image: "/projects/gamified-learning.png",
      highlights: [
        "XP-based leveling system with mastery tracking",
        "Live missions and performance pulse analytics",
        "Leaderboard and learning streak mechanics",
      ],
      github: "https://github.com/awanishkrai",
    },
    {
      name: "AlgoPhoto",
      description:
        "Algorithmic image processing system focused on pixel-level transformations.",
      technologies: "Python, Dynamic Programming, Image Processing",
      image: "/projects/algophoto.png",
      highlights: [
        "Implements dynamic programming based transformations without heavy CV libraries",
        "Supports batch processing and custom filter pipelines",
        "Optimized for performance on large images",
      ],
      github: "https://github.com/awanishkrai",
    },
  ],
  certifications: [
    {
      name: "Computer Communications",
      institution: "University of Colorado",
      platform: "Coursera",
      date: "Nov 13, 2024",
      verifyUrl: "https://coursera.org/verify/specialization/VGVH7V0F8RH8",
      type: "specialization",
      image: "/certificates/computer-communications.png",
      courses: [
        "Fundamentals of Network Communication",
        "Peer-to-Peer Protocols and Local Area Networks",
        "Packet Switching Networks and Algorithms",
        "TCP/IP and Advanced Topics",
      ],
    },
    {
      name: "Fundamentals of Network Communication",
      institution: "University of Colorado",
      platform: "Coursera",
      date: "Sep 25, 2024",
      verifyUrl: "https://coursera.org/verify/JLP5C1V4ZYI0",
      type: "course",
      image: "/certificates/network-communication.png",
    },
    {
      name: "Packet Switching Networks and Algorithms",
      institution: "University of Colorado",
      platform: "Coursera",
      date: "Oct 30, 2024",
      verifyUrl: "https://coursera.org/verify/GAY60G7LPA1H",
      type: "course",
      image: "/certificates/packet-switching.png",
    },
    {
      name: "Digital Systems: From Logic Gates to Processors",
      institution: "Universitat Autònoma de Barcelona",
      platform: "Coursera",
      date: "Sep 24, 2024",
      verifyUrl: "https://coursera.org/verify/TV278LUU5RMK",
      type: "course",
      image: "/certificates/digital-systems.png",
    },
    {
      name: "The Bits and Bytes of Computer Networking",
      institution: "Google",
      platform: "Coursera",
      date: "Sep 7, 2024",
      verifyUrl: "https://coursera.org/verify/UTO26UAYFC93",
      type: "course",
      image: "/certificates/bits-bytes-networking.png",
    },
    {
      name: "Introduction to Hardware and Operating Systems",
      institution: "IBM",
      platform: "Coursera",
      date: "Sep 13, 2024",
      verifyUrl: "https://coursera.org/verify/U8Q1RBPC2YWU",
      type: "course",
      image: "/certificates/hardware-os.png",
    },
  ],
  terminal: {
    commands: {
      whoami: "Awanish Kumar Rai",
      whoami_full: "Computer Science Undergraduate | Software Engineer",
      projects: "OS-Room-Booking-System | Adhyay | Neo-Gamified-Learning | AlgoPhoto",
      skills: "Python, C++, React, Django, PostgreSQL, MongoDB, and more...",
      socials:
        "GitHub: github.com/awanishkrai | LinkedIn: linkedin.com/in/awanish-rai-9296ab221",
      help: "Available commands: whoami, projects, skills, socials, clear, help, contact",
      contact: "Email: awanishrai420@gmail.com | Phone: +91-6283642238",
    },
  },
};
